FROM ubuntu:22.04

# 도구 설치 및 ION 설치
RUN apt-get update && apt-get install -y build-essential git automake libtool pkg-config iproute2 iputils-ping python3 python3-pip
WORKDIR /opt
RUN git clone https://github.com/nasa-jpl/ION-DTN.git && cd ION-DTN && ./configure && make && make install && ldconfig

# 환경 설정
WORKDIR /app
RUN pip3 install flask
COPY . . 
RUN chmod +x start_mars.sh

CMD ["./start_mars.sh"]